### ISSUE TITLE
Individual team member page has incorrect breakpoints

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#111]
Our individual team member page has a slight discrepancy in the breakpoints; take [mine](https://teachla.uclaacm.com/team/mattwang):

At 855px:

![Screen Shot 2020-10-14 at 9 13 15 PM](https://user-images.githubusercontent.com/14893287/96076391-1a8d8c00-0e62-11eb-9e68-1116010e0913.png)

At 844px (this is the undesirable behaviour)

![Screen Shot 2020-10-14 at 9 13 39 PM](https://user-images.githubusercontent.com/14893287/96076420-27aa7b00-0e62-11eb-8b4f-045238d84e49.png)

At <800px

![Screen Shot 2020-10-14 at 9 13 58 PM](https://user-images.githubusercontent.com/14893287/96076444-33963d00-0e62-11eb-9ec1-fb4ede0eea68.png)

If I had to guess, this would be a finicky `@media` query, maybe using a mismatched set of values; note that `$desktop-width` is `850px`, which explains the first jump, but not the second `800px` jump. Needs some investigation, but is a good first issue to get someone started!

**Comment by surreally** [comment]
When the viewport width goes under 850px, `.col` elements lose their left and right padding (of `1em` each), leading to the presentation in Fig. 2 with no gap between the image and the profile text. When the viewport width shrinks further, the `.row` container starts to wrap, leading to Fig. 3.
Easy solution would be to change `.row` elements’ `flex-direction` to `column` (and restrict the size of the image if necessary, otherwise the image will flood the whole screen when the viewport is still relatively wide, say 800px) when it’s mobile. Another possible solution is to add `margin-right` to `.col` elements when the viewport is narrow to force wrap the two, but it will break every other page, e.g. the homepage. Adding padding regardless of viewport width also breaks the homepage. :/

**Comment by malsf21** [comment]
Hey Jun,

Totally sorry that I dropped the ball on this issue! Thank you again for diving deep into this issue.

I'll be honest, the original `.row` and `.col` classes are poorly designed: they're a result from me scrapping together major elements of the website within an hour. I think overall, we probably need to refactor our entire grid system (there are quite a few confusing grid classes).

In terms of the resolution for this problem in particular, what would you prefer to do @surreally? If you are interested in adjusting the overall classes, we can do that; we can also do a band-aid fix and override the `.row` and `.col` styles for this specific page, and reevaluate our options later down the line. Let me know what you think!

**Comment by surreally** [comment]
Been a while, thought someone would've taken this but I'll do it! I suggest an easy patch for now just to fix the looks and open another issue to take a closer look at the `.row` and `.col` (and `.grid-row` and `.grid-col`) classes. I'll do it sometime this week, since I've already figured out what the problem is. Shouldn't be hard.

**Comment by surreally** [comment]
I didn't get to fix this but seems like it's been resolved!

**Comment by malsf21** [comment]
Are you sure? I can still replicate it on live for me.

**Comment by surreally** [comment]
I don't see the 844px undesired result
<img width="886" alt="Screen Shot 2021-01-02 at 11 49 46 PM" src="https://user-images.githubusercontent.com/48810180/103474091-331c8c80-4d55-11eb-9eb8-c82787276bbf.png">
This is on Brave. The same on Firefox and Safari for me

**Comment by malsf21** [comment]
Huh, so it doesn't show up for mine (or I think, anything with content under the role title). Take a peep at Bonnie's though:

![Uploading Screen Shot 2021-01-02 at 11.55.10 PM.png…]()

**Comment by surreally** [comment]
This is odd. I'll do it tomorrow. (We should also encourage everybody to write bios!)
