### ISSUE TITLE
RSS Blog Feed

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#178]
Depending on how the rest of ACM manages their blogging infrastructure, an RSS feed may be helpful. Regardless, it's a nice-to-have feature that shouldn't have much maintenance cost!

**Comment by krashanoff** [comment]
For people interested in tackling this, check out [jekyll-feed](https://github.com/jekyll/jekyll-feed), a Jekyll plugin that automatically generates an RSS feed. This plugin would simplify things, though it may require changes to our author key/val pairs. A guide on using it can be found [here](https://www.r-bloggers.com/2019/12/creating-an-rss-feed-to-add-your-jekyll-github-pages-blog-to-r-bloggers/).

**Comment by Stephanie0829** [comment]
Couple questions from following the guide:

1. For the email for author, is there a preferred email I should place
2. Is there a preferred tag to indicate that a given post is suitable for the blog

**Comment by malsf21** [comment]
Great questions!

1. For the author, if the blog post's author has an email (you can perform this with a lookup into the teams collection - let me know if you want help with this), we can use that. If not, feel free to use `acmteachla@gmail.com` for now!
2. Do you mind clarifying what you mean? I would say all posts are suitable for the blog, but I might be missing something.

**Comment by Stephanie0829** [comment]
Yes! The guide had specified the [“R”] tag, meaning all posts with that tag would be included in the RSS feed.

**Comment by malsf21** [comment]
Oh I see! For that guide, they were looking to only add posts tagged with `"R"` to the RSS feed. In our case, I think we should do all the posts. You can do that with `site in site.posts` instead!

**Comment by Stephanie0829** [comment]
I also want to mention that there were a couple of things I had to alter from the code that the guide had told to directly copy and paste. 
- the guide had this segment of code before the xml declaration
              - <code>---
              layout: null
              ---
- and this segment of code after the xml segment of the code
             </code>
- I realized that after compiling the site and going to the feed, it displayed an error saying that "XML declaration allowed only at the start of the document", so I deleted these lines of code and the error disappeared (not sure if this was the correct solution since I honestly was not too sure about the purpose of those lines of code)

- There was also an error about an "attributes construct error", which I fixed from changing 
                     ..... some code......"{{ "/feed.rbloggers.xml"......some code....
to:
                                                   "{{ '/feed.rbloggers.xml'

**Comment by malsf21** [comment]
Yup, that's totally fine! The guide is just a helpful resource / suggestion - at the end of the day, it is just a random guide made by somebody on the internet! As you submit your pull request, I can give you direct feedback on your code, but until then - just focus on making it work to a standard that you're confident in!

**Comment by Stephanie0829** [comment]
Sounds good! Thank you!
