### ISSUE TITLE
Fix Link Background Bug

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#96]
Currently, our "fancy" link (the `tla-link` mixin in `_basic.scss`) has a small bug: the background white of the linear gradient is a bit too large, and hits text in the line above it. See below:

![Screen Shot 2020-10-04 at 6 02 47 PM](https://user-images.githubusercontent.com/14893287/95031626-e8af4500-066b-11eb-8fb1-bf9392f2c559.png)

The "Fill out our interest form" is having its lower bounding box being cutoff by the white part of the linear gradient.

To resolve this issue, we can probably play around with different one-line solutions:

* simplest solution: reduce size of the background, may involve some tweaking
* consider: adjust background element to have a lower z-index, so the white is overlapped by other elements

This is a tricky bug in the sense that it's not very visible, but causes problems with different font sizes, link stacking, etc. That being said, I think it's a simple one-line fix - a great place to start!

P.S. for bonus points, you can refactor the mixin out of `_basic.scss` into its own file, for good practice.

**Comment by malsf21** [comment]
Left to @surreally

**Comment by surreally** [comment]
I played around with it a couple of days ago and the problem seems to be the `<a>` elements are displayed inline, which makes the boxes taller than what they should be, since there's no margin, border or padding but [the content box height > font size](https://stackoverflow.com/questions/28363186/inline-elements-and-line-height). So two things seemed to work:
- Increase the line height of all `<p>` elements, but that's a big change
- Make `<a>` elements `inline-block`, but obviously it wouldn't flow in the paragraphs anymore
Or I just haven't figured out how to change just the size or the z-index of the background of some element.

**Comment by surreally** [comment]
Todo: 

- try pseudo after elements
- cancel linear gradient and essentially use a green block that changes position (moves up) when hovering and is tucked under when normal
